SCAMonitor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCAMonitor.Controllers {
	public class HomeController : Controller {
		public ActionResult Index() {
			return View();
		}

		public ActionResult About() {
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact() {
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

SCAMonitor/Controllers/MonitorBarragemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCA.Controllers
{
	public class MonitorBarragemController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Title = "SCA - Monitoramento de Barragens";

			return View();
		}
	}
}

SCAMonitor/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SCAMonitor/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SCAMonitor/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SCA";
}

<div class="jumbotron">
    <h1>SCA - Monitor de Barragens</h1>
</div>

SCAMonitor/Views/MonitorBarragem/Index.cshtml
<div class="jumbotron">
	<h1>Monitoramento de Barragens</h1>
</div>

<div class="container">
	<form>
		<div class="form-group">
			<label for="idBarragem" class="col-form-label">Barragem:</label>
			<select name="idBarragem" id="idBarragem"></select>
		</div>
		<div class="form-group">
			<label for="idSensor" class="col-form-label">Sensor:</label>
			<select name="idSensor" id="idSensor">
				<option value="">Selecione...</option>
			</select>
		</div>
	</form>
	<div class="mt-1">
		<div style="width: 600px; height: 600px;">
			<canvas id="chartSensor"></canvas>
		</div>
	</div>
</div>



@section Scripts {
	<script language="javascript">		
		var sensorChart = null;

		var baseURL = @Html.Raw(HttpUtility.JavaScriptStringEncode(System.Configuration.ConfigurationManager.AppSettings["UrlBaseSCA"].ToString(), true));

		var vetorRGB = [];
		vetorRGB[0] = "0, 255, 0";
		vetorRGB[1] = "0, 0, 255";
		vetorRGB[2] = "255, 0, 0";
		vetorRGB[3] = "255, 255, 0";
		vetorRGB[4] = "255, 0, 255";

		$(document).ready(function () {
			recuperarBarragens();

			$("#idBarragem").on("change", function () {
				if ($(this).val() != "") {
					recuperarSensores($(this).val());
				}
			});

			$("#idSensor").on("change", function () {
				if ($(this).val() != "") {
					recuperarLogSensor($(this).val());
				}
			});
		});

		function recuperarBarragens() {
			$.ajax({
				method: "GET",
				url: baseURL + "api/barragem",
				dataType: "json",
				async: false
			})
			.done(function (data) {
				carregarBarragens(data);
			});
		}

		function carregarBarragens(barragens) {
			$("#idBarragem").append($("<option />").val("").text("Selecione...").attr("selected", "selected"));

			$(barragens).each(function (index, barragem) {
				$("#idBarragem").append($("<option />").val(barragem.ID).text(barragem.Name));
			});
		}		

		function recuperarSensores(idBarragem) {
			$.ajax({
				method: "GET",
				url: baseURL + "api/sensor/barragem/" + idBarragem,
				dataType: "json"
			})
			.done(function (data) {
				carregarSensores(data);
			});
		}

		function carregarSensores(sensores) {
			$("#idSensor").find("option").remove();

			if (sensorChart != null) {
				sensorChart.destroy();
			}

			$("#idSensor").append($("<option />").val("").text("Selecione...").attr("selected", "selected"));

			$(sensores).each(function (index, sensor) {
				$("#idSensor").append($("<option />").val(sensor.ID).text(sensor.Name));
			});

			$("#idSensor").append($("<option />").val("0").text("Todos"));
		}

		function recuperarLogSensor(idSensor) {
			$.ajax({
				method: "GET",
				url: baseURL + "api/logsensor/" + $("#idBarragem").val() + "/" + idSensor + "/ocorrencia",
				dataType: "json"
			})
			.done(function (data) {
				processarLogSensor(data);
			});
		}

		function processarLogSensor(ocorrenciasSensor) {
			var datasets = [];

			var dataSensor = new Array();

			$(ocorrenciasSensor).each(function (index, ocorrenciaSensor) {
				var dataSensor = new Array();

				$(ocorrenciaSensor.Ocorrencias).each(function (index, ocorrencia) {
					dataSensor.push(ocorrencia.Quantidade);
				});

				datasets[index] = {
					label: ocorrenciaSensor.Sensor.Name,
					data: dataSensor,
					fill: false,
					backgroundColor: "rgba(" + vetorRGB[index % vetorRGB.length] + ", 0.5)",
					borderWidth: 1
				};
				
			});

			if (sensorChart != null) {
				sensorChart.destroy();
			}

			sensorChart = new Chart(
				$("#chartSensor"), {
				type: "bar",
					data: {
						labels: ["Segurança", "Alerta", "Emergência"],
						datasets: datasets
					},
					options: {
						scales: {
							xAxes: [{
								scaleLabel: {
									display: true,
									labelString: "Status do sensor"
								}
							}],
							yAxes: [{
								ticks: { beginAtZero: true },
								scaleLabel: {
									display: true,
									labelString: "Ocorrências"
								}
							}]
						}
					}
			});
		}


	</script>
}

SCAMonitor/Views/Shared/_Layout.cshtml
@{
    var imagePath = "~/Content/Images/";

    var spinerPath = imagePath + "spiner.gif";

	var urlToken = Html.Raw(HttpUtility.JavaScriptStringEncode(System.Configuration.ConfigurationManager.AppSettings["UrlBaseSCA"].ToString() + "token", true));
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/OAuthClient")
    @Scripts.Render("~/bundles/store.js")
    @Scripts.Render("~/bundles/jquery.oauth")
    <script language="javascript">
		var storage;
		var urlToken = @urlToken;

		$(document).ready(function () {
			storage = store;

			var oAuthClient = new OAuthClient(urlToken);
			oAuthClient._login();
		});
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SCA - Monitor de Barragens", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Monitoramento de Barragens", "Index", "MonitorBarragem", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="divCarregando">
            <div class=""><img src=@Url.Content(spinerPath) /></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SCA - Monitor de Barragens</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/json")
    @Scripts.Render("~/bundles/jquery.mask")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Chart.js")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>