SCA/Controllers/CadastroAtivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCA.Controllers
{
	public class CadastroAtivoController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Title = "SCA - Cadastro de Ativos";

			return View();
		}
	}
}

SCA/Controllers/CadastroSensorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SCA.Controllers
{
	public class CadastroSensorController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Title = "SCA - Cadastro de Sensor";

			return View();
		}
	}
}

SCA/Views/Shared/_Layout.cshtml
@{ 
	string imagePath = "~/Content/Images/";

	string spinerPath = imagePath + "spiner.gif";

	var urlToken = Html.Raw(HttpUtility.JavaScriptStringEncode(
			new Uri(
					new Uri(this.Context.Request.Url.GetLeftPart(UriPartial.Authority)),
					Url.Content("~/token")
				).ToString(), true));
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/OAuthClient")
    @Scripts.Render("~/bundles/store.js")
    @Scripts.Render("~/bundles/jquery.oauth")
    <script language="javascript">
		var storage;

		var urlToken = @urlToken;

		$(document).ready(function () {
			storage = store;

			var oAuthClient = new OAuthClient(urlToken);
			oAuthClient._login();			
		});
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SCA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Ativos", "Index", "CadastroAtivo", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cadastro de Barragens", "Index", "CadastroBarragem", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Cadastro de Sensores", "Index", "CadastroSensor", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="divCarregando">
            <div class=""><img src=@Url.Content(spinerPath) /></div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - SCA</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/json")
    @Scripts.Render("~/bundles/jquery.mask")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Chart.js")
    @Scripts.Render("~/bundles/lib_input_validator")
    @Scripts.Render("~/bundles/lib_date_functions")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>